# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Database Operator" `
  org.label-schema.vendor="Kubehippie" `
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["c:\\database-operator.exe"]

COPY bin/database-operator.exe c:\database-operator.exe
