---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: operator
  namespace: database-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccount: operator
      containers:
      - name: operator
        image: kubehippie/database-operator:1.0.0-alpha1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
