---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: database-operator
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - webhippie.de
  resources:
  - operator
  - operator.webhippie.de
  verbs:
  - create
  - update
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
